package de.csw.turtle.api.security

enum class Permission {
    API_LOCKERS_CREATE,
    API_LOCKERS_GET,
    API_LOCKERS_PATCH,
    API_LOCKERS_DELETE,

    API_USERS_CREATE,
    API_USERS_GET,
    API_USERS_PATCH,
    API_USERS_DELETE,

    API_DEVICES_CREATE,
    API_DEVICES_GET,
    API_DEVICES_PATCH,
    API_DEVICES_DELETE,

    API_DEVICES_CATEGORIES_CREATE,
    API_DEVICES_CATEGORIES_GET,
    API_DEVICES_CATEGORIES_PATCH,
    API_DEVICES_CATEGORIES_DELETE,

    API_SUPPORT_CREATE,
    API_SUPPORT_GET,
    API_SUPPORT_DELETE,

    API_EXCEPTIONS_GET,
    API_EXCEPTIONS_DELETE,

    API_AUTH_REGISTER,
    API_AUTH_LOGIN,
    API_AUTH_LOGOUT,

    API_PROFILE_GET,
    API_PROFILE_PATCH,
    API_PROFILE_DELETE,

    API_AUDITLOGS_GET,

    DEBUG_EXCEPTION,
    DEBUG_INFO,
    DEBUG_LOCKER,
    DEBUG_DOOR,
    DEBUG_EMAIL
}