package de.csw.turtle.api

enum class Permission {
    MANAGE_AUDIT_LOGS,
    MANAGE_DOOR,
    MANAGE_ITEM_CATEGORIES,
    MANAGE_ITEMS,
    MANAGE_EXCEPTIONS,
    MANAGE_LOCKERS,
    MANAGE_SUPPORT_TICKETS,
    MANAGE_ROLES,
    MANAGE_USERS,
    MANAGE_EMAIL_TEMPLATES,
    MANAGE_GENERAL_TEMPLATES,
    MANAGE_FAQ,
    MANAGE_ROOM_BOOKINGS,
    MANAGE_ITEM_BOOKINGS,
    MANAGE_SYSTEM_SETTINGS,
    MANAGE_TOKENS,

    REQUEST_ROOM_BOOKINGS
}
