package de.csw.turtle.api

/*
 * The permission names follow a simple format:
 *
 * Scenario: We want to create a permission for a user login
 *
 * ENVIRONMENT = FRONTEND / BACKEND
 * ENDPOINT = The corresponding endpoint, defined by the controller (/api/auth), separated by an underscore (_) except slashes (/), e.g. /api/auth/login -> API_AUTH
 * ACTION = A simple string to identify what the permission does, e.g. when logging in -> LOGIN
 *
 * {ENVIRONMENT}__{ENDPOINT}__{ACTION} -> BACKEND__API_AUTH__LOGIN
 */

enum class Permission {

    BACKEND__DEBUG__DOOR,
    BACKEND__DEBUG__LOCKER,
    BACKEND__DEBUG__EXCEPTION,
    BACKEND__DEBUG__EMAIL,
    BACKEND__DEBUG__INFO,

    BACKEND__API_USER_PROFILE__GET,
    BACKEND__API_USER_PROFILE__PATCH,
    BACKEND__API_USER_PROFILE__DELETE,

    MANAGE_AUDIT_LOGS,
    MANAGE_DEVICE_CATEGORIES,
    MANAGE_DEVICES,
    MANAGE_EXCEPTIONS,
    MANAGE_LOCKERS,
    MANAGE_SUPPORT_TICKETS,
    MANAGE_ROLES,
    MANAGE_USERS,
    MANAGE_TEMPLATES,
    MANAGE_FAQ,
    MANAGE_ROOM_BOOKINGS,
    MANAGE_DEVICE_BOOKINGS,
    MANAGE_SYSTEM_SETTINGS,

    BACKEND__API_HARDWARE__DOOR,
    BACKEND__API_HARDWARE__LOCKER,

    FRONTEND__SIDEBAR_CATEGORY__PUBLIC,
    FRONTEND__SIDEBAR_ITEM__HOME,
    FRONTEND__SIDEBAR_ITEM__LOGIN,
    FRONTEND__SIDEBAR_ITEM__REGISTER,
    FRONTEND__SIDEBAR_ITEM__SUPPORT,
    FRONTEND__SIDEBAR_ITEM__FAQ,
    FRONTEND__SIDEBAR_ITEM__ABOUT,

    FRONTEND__SIDEBAR_CATEGORY__USER,
    FRONTEND__SIDEBAR_ITEM__DASHBOARD,
    FRONTEND__SIDEBAR_ITEM__PROFILE,
    FRONTEND__SIDEBAR_ITEM__BOOK_DEVICE,
    FRONTEND__SIDEBAR_ITEM__BOOK_ROOM,

    FRONTEND__SIDEBAR_CATEGORY__ADMINISTRATOR,
    FRONTEND__SIDEBAR_ITEM__MANAGE_USERS,
    FRONTEND__SIDEBAR_ITEM__MANAGE_SUPPORT_TICKETS,
    FRONTEND__SIDEBAR_ITEM__MANAGE_EXCEPTIONS,
    FRONTEND__SIDEBAR_ITEM__MANAGE_ROOM_BOOKINGS,
    FRONTEND__SIDEBAR_ITEM__MANAGE_DEVICE_BOOKINGS,
    FRONTEND__SIDEBAR_ITEM__MANAGE_NEWS,
    FRONTEND__SIDEBAR_ITEM__MANAGE_AUDIT_LOGS,
    FRONTEND__SIDEBAR_ITEM__MANAGE_ROLES,
    FRONTEND__SIDEBAR_ITEM__MANAGE_TEMPLATES

}
