package de.csw.turtle.api

enum class Permission {

    DEBUG__DOOR,
    DEBUG__LOCKER,
    DEBUG__EXCEPTION,
    DEBUG__EMAIL,
    DEBUG__INFO,

    API_AUDITLOGS__GET,

    API_DEVICECATEGORIES__CREATE,
    API_DEVICECATEGORIES__GET,
    API_DEVICECATEGORIES__PATCH,
    API_DEVICECATEGORIES__DELETE,

    API_DEVICES__CREATE,
    API_DEVICES__GET,
    API_DEVICES__PATCH,
    API_DEVICES__DELETE,

    API_EXCEPTIONS__GET,
    API_EXCEPTIONS__DELETE,

    API_LOCKERS__CREATE,
    API_LOCKERS__GET,
    API_LOCKERS__PATCH,
    API_LOCKERS__DELETE,

    API_SUPPORTTICKETS__CREATE,
    API_SUPPORTTICKETS__GET,
    API_SUPPORTTICKETS__PATCH,
    API_SUPPORTTICKETS__DELETE,

    API_USERS__CREATE,
    API_USERS__GET,
    API_USERS__PATCH,
    API_USERS__DELETE,

    API_ROLES__CREATE,
    API_ROLES__GET,
    API_ROLES__PATCH,
    API_ROLES__DELETE,

    //Permissions relevant for frontend (e.g. VIEW_ADMINISTRATOR is responsible for displaying the admin accordion on the layout)
    VIEW_ADMINISTRATOR;

}
