import * as db from '$lib/server/users/UserDatabase.js';
import {json} from '@sveltejs/kit';

export async function GET({request}) {
    const payload = {
        "id": 129,
        "username": "admin",
        "firstName": "admin",
        "lastName": "admin",
        "email": "admin@csw.de",
        "studentId": 42069,
        "roles": [{"id": 4, "name": "Administrator"}],
        "permissions": ["BACKEND__API_AUDITLOGS__GET", "BACKEND__API_AUTH__LOGIN", "BACKEND__API_AUTH__LOGOUT", "BACKEND__API_AUTH__REGISTER", "BACKEND__API_DEVICECATEGORIES__CREATE", "BACKEND__API_DEVICECATEGORIES__DELETE", "BACKEND__API_DEVICECATEGORIES__GET", "BACKEND__API_DEVICECATEGORIES__PATCH", "BACKEND__API_DEVICES__CREATE", "BACKEND__API_DEVICES__DELETE", "BACKEND__API_DEVICES__GET", "BACKEND__API_DEVICES__PATCH", "BACKEND__API_EXCEPTIONS__DELETE", "BACKEND__API_EXCEPTIONS__GET", "BACKEND__API_LOCKERS__CREATE", "BACKEND__API_LOCKERS__DELETE", "BACKEND__API_LOCKERS__GET", "BACKEND__API_LOCKERS__PATCH", "BACKEND__API_ROLES__CREATE", "BACKEND__API_ROLES__DELETE", "BACKEND__API_ROLES__GET", "BACKEND__API_ROLES__PATCH", "BACKEND__API_SUPPORTTICKETS__CREATE", "BACKEND__API_SUPPORTTICKETS__DELETE", "BACKEND__API_SUPPORTTICKETS__GET", "BACKEND__API_SUPPORTTICKETS__PATCH", "BACKEND__API_USERS__CREATE", "BACKEND__API_USERS__DELETE", "BACKEND__API_USERS__GET", "BACKEND__API_USERS__PATCH", "BACKEND__API_USER_PROFILE__DELETE", "BACKEND__API_USER_PROFILE__GET", "BACKEND__API_USER_PROFILE__PATCH", "BACKEND__DEBUG__DOOR", "BACKEND__DEBUG__EMAIL", "BACKEND__DEBUG__EXCEPTION", "BACKEND__DEBUG__INFO", "BACKEND__DEBUG__LOCKER", "FRONTEND__VIEW_ADMINISTRATOR"],
        "createdAt": "2025-11-30T22:31:25.328625Z"
    }

    return json(payload);
}