CREATE TABLE audit_logs (
                                   status integer NOT NULL,
                                   created_at timestamp(6) with time zone,
                                   id bigint NOT NULL,
                                   updated_at timestamp(6) with time zone,
                                   user_id bigint,
                                   endpoint character varying(255),
                                   http_method character varying(255),
                                   ip_address character varying(255),
                                   CONSTRAINT audit_logs_http_method_check CHECK (((http_method)::text = ANY ((ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'DELETE'::character varying, 'HEAD'::character varying, 'OPTIONS'::character varying, 'TRACE'::character varying, 'PATCH'::character varying])::text[])))
);

ALTER TABLE audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE configuration (
                                      created_at timestamp(6) with time zone,
                                      id bigint NOT NULL,
                                      updated_at timestamp(6) with time zone,
                                      key character varying(255),
                                      type character varying(255),
                                      value character varying(255),
                                      visibility character varying(255),
                                      CONSTRAINT configuration_key_check CHECK (((key)::text = ANY ((ARRAY['GENERAL_FQDN'::character varying, 'EMOJIS_ALL'::character varying, 'EMOJIS_SIZE'::character varying, 'EMOJIS_MAX_RETRIES'::character varying, 'USER_VERIFICATION_DURATION'::character varying, 'USER_EMAIL_TRUSTED'::character varying, 'USER_PASSWORD_REGEX'::character varying, 'ALTCHA_ENABLED'::character varying, 'ALTCHA_SECRET'::character varying, 'ALTCHA_MAX_NUMBER'::character varying, 'ALTCHA_DURATION'::character varying, 'ALTCHA_TRUSTED_IPS'::character varying, 'DOOR_DEBUG_ENABLED'::character varying, 'DOOR_OPEN_DURATION'::character varying, 'DOOR_SCHEDULE_START'::character varying, 'DOOR_SCHEDULE_END'::character varying, 'DOOR_SSH_COMMAND'::character varying, 'DOOR_SSH_HOSTNAME'::character varying, 'DOOR_SSH_PORT'::character varying, 'DOOR_SSH_USERNAME'::character varying, 'DOOR_SSH_PASSWORD'::character varying, 'LOCKER_DEBUG_ENABLED'::character varying, 'LOCKER_SCHEDULE_START'::character varying, 'LOCKER_SCHEDULE_END'::character varying, 'LOCKER_SSH_COMMAND'::character varying, 'LOCKER_SSH_HOSTNAME'::character varying, 'LOCKER_SSH_PORT'::character varying, 'LOCKER_SSH_USERNAME'::character varying, 'LOCKER_SSH_PASSWORD'::character varying, 'JWT_SECRET'::character varying, 'JWT_DURATION_ACCESS'::character varying, 'JWT_DURATION_REFRESH'::character varying, 'SUPPORT_TICKET_SUBJECT_LENGTH'::character varying, 'SUPPORT_TICKET_DESCRIPTION_LENGTH'::character varying, 'SUPPORT_TICKET_CATEGORY_NAME_LENGTH'::character varying, 'SUPPORT_TICKET_URGENCY_NAME_LENGTH'::character varying, 'ROOM_BOOKING_TITLE_LENGTH'::character varying, 'ROOM_BOOKING_DESCRIPTION_LENGTH'::character varying, 'ITEM_NAME_LENGTH'::character varying, 'ITEM_DESCRIPTION_LENGTH'::character varying, 'ITEM_BOOKING_MAX_SIMULTANEOUS'::character varying, 'ITEM_CATEGORY_NAME_LENGTH'::character varying, 'FAQ_NAME_LENGTH'::character varying, 'FAQ_TITLE_LENGTH'::character varying, 'URL_X'::character varying, 'URL_INSTAGRAM'::character varying, 'URL_GITHUB'::character varying, 'SECURITY_BCRYPT_STRENGTH'::character varying])::text[]))),
    CONSTRAINT configuration_type_check CHECK (((type)::text = ANY ((ARRAY['BOOLEAN'::character varying, 'INT'::character varying, 'INT_LIST'::character varying, 'LONG'::character varying, 'LONG_LIST'::character varying, 'FLOAT'::character varying, 'FLOAT_LIST'::character varying, 'DOUBLE'::character varying, 'DOUBLE_LIST'::character varying, 'STRING'::character varying, 'STRING_LIST'::character varying, 'DATE'::character varying, 'TIME'::character varying, 'INSTANT'::character varying, 'DURATION'::character varying])::text[]))),
    CONSTRAINT configuration_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])))
);

ALTER TABLE configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE content_templates (
                                          created_at timestamp(6) with time zone,
                                          id bigint NOT NULL,
                                          updated_at timestamp(6) with time zone,
                                          content text,
                                          description text,
                                          name character varying(255),
                                          type character varying(255),
                                          CONSTRAINT content_templates_type_check CHECK (((type)::text = ANY ((ARRAY['IMPRINT'::character varying, 'GENERAL_DATA_PROTECTION_REGULATION'::character varying, 'TERMS_OF_SERVICE'::character varying, 'ABOUT'::character varying, 'CONTACT'::character varying])::text[])))
);

ALTER TABLE content_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME content_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE email_templates (
                                        created_at timestamp(6) with time zone,
                                        id bigint NOT NULL,
                                        updated_at timestamp(6) with time zone,
                                        content text,
                                        description text,
                                        name character varying(255),
                                        subject character varying(255),
                                        type character varying(255),
                                        CONSTRAINT email_templates_type_check CHECK (((type)::text = ANY ((ARRAY['USER_CREATED'::character varying, 'USER_VERIFICATION'::character varying, 'USER_PASSWORD_RESET'::character varying, 'ROOM_BOOKING_CREATED'::character varying, 'ROOM_BOOKING_UPDATED'::character varying])::text[])))
);

ALTER TABLE email_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME email_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE exceptions (
                                   created_at timestamp(6) with time zone,
                                   id bigint NOT NULL,
                                   updated_at timestamp(6) with time zone,
                                   endpoint character varying(255),
                                   exception character varying(255),
                                   message text,
                                   stack_trace text
);

ALTER TABLE exceptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME exceptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE faq (
                            enabled boolean NOT NULL,
                            created_at timestamp(6) with time zone,
                            id bigint NOT NULL,
                            updated_at timestamp(6) with time zone,
                            content text,
                            name character varying(255),
                            title character varying(255)
);

ALTER TABLE faq ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME faq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE item_bookings (
                                      collected_at timestamp(6) with time zone,
                                      created_at timestamp(6) with time zone,
                                      end_time timestamp(6) with time zone,
                                      id bigint NOT NULL,
                                      item_id bigint,
                                      returned_at timestamp(6) with time zone,
                                      start_time timestamp(6) with time zone,
                                      updated_at timestamp(6) with time zone,
                                      user_id bigint,
                                      status character varying(255),
                                      CONSTRAINT item_bookings_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying, 'PENDING_COLLECTION'::character varying, 'COLLECTED'::character varying, 'PENDING_RETURN'::character varying, 'RETURNED'::character varying, 'COMPLETED'::character varying])::text[])))
);

ALTER TABLE item_bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME item_bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE item_categories (
                                        created_at timestamp(6) with time zone,
                                        id bigint NOT NULL,
                                        updated_at timestamp(6) with time zone,
                                        name character varying(255)
);

ALTER TABLE item_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME item_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE items (
                              needs_confirmation boolean NOT NULL,
                              acquired_at timestamp(6) with time zone,
                              category_id bigint,
                              created_at timestamp(6) with time zone,
                              id bigint NOT NULL,
                              locker_id bigint,
                              updated_at timestamp(6) with time zone,
                              description text,
                              name character varying(255)
);

ALTER TABLE items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE lockers (
                                index integer,
                                is_software_unlockable boolean NOT NULL,
                                locked boolean NOT NULL,
                                created_at timestamp(6) with time zone,
                                id bigint NOT NULL,
                                updated_at timestamp(6) with time zone,
                                name character varying(255)
);

ALTER TABLE lockers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lockers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE posts (
                              enabled boolean NOT NULL,
                              created_at timestamp(6) with time zone,
                              id bigint NOT NULL,
                              updated_at timestamp(6) with time zone,
                              content text,
                              description character varying(255),
                              name character varying(255),
                              title character varying(255)
);

ALTER TABLE posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE role_permissions (
                                         role_id bigint NOT NULL,
                                         permission character varying(255),
                                         CONSTRAINT role_permissions_permission_check CHECK (((permission)::text = ANY ((ARRAY['MANAGE_AUDIT_LOGS'::character varying, 'MANAGE_DOOR'::character varying, 'MANAGE_ITEM_CATEGORIES'::character varying, 'MANAGE_ITEMS'::character varying, 'MANAGE_EXCEPTIONS'::character varying, 'MANAGE_LOCKERS'::character varying, 'MANAGE_SUPPORT_TICKETS'::character varying, 'MANAGE_ROLES'::character varying, 'MANAGE_USERS'::character varying, 'MANAGE_EMAIL_TEMPLATES'::character varying, 'MANAGE_GENERAL_TEMPLATES'::character varying, 'MANAGE_FAQ'::character varying, 'MANAGE_ROOM_BOOKINGS'::character varying, 'MANAGE_ITEM_BOOKINGS'::character varying, 'MANAGE_CONFIGURATION'::character varying, 'MANAGE_TOKENS'::character varying, 'MANAGE_STATISTIC_QUERIES'::character varying, 'MANAGE_SUPPORT_TICKET_CATEGORIES'::character varying, 'MANAGE_SUPPORT_TICKET_URGENCIES'::character varying, 'MANAGE_POSTS'::character varying, 'REQUEST_ROOM_BOOKINGS'::character varying])::text[])))
);

CREATE TABLE roles (
                              created_at timestamp(6) with time zone,
                              id bigint NOT NULL,
                              updated_at timestamp(6) with time zone,
                              name character varying(255),
                              type character varying(255),
                              CONSTRAINT roles_type_check CHECK (((type)::text = ANY ((ARRAY['STUDENT'::character varying, 'PROFESSOR'::character varying, 'ADMINISTRATOR'::character varying])::text[])))
);

ALTER TABLE roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE room_bookings (
                                      created_at timestamp(6) with time zone,
                                      end_time timestamp(6) with time zone,
                                      id bigint NOT NULL,
                                      start_time timestamp(6) with time zone,
                                      updated_at timestamp(6) with time zone,
                                      user_id bigint,
                                      access character varying(255),
                                      description text,
                                      status character varying(255),
                                      title character varying(255),
                                      CONSTRAINT room_bookings_access_check CHECK (((access)::text = ANY ((ARRAY['LOCKED'::character varying, 'WHITELIST'::character varying, 'UNLOCKED'::character varying])::text[]))),
    CONSTRAINT room_bookings_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))
);

ALTER TABLE room_bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME room_bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE room_bookings_whitelisted_users (
                                                        room_booking_id bigint NOT NULL,
                                                        user_id bigint NOT NULL
);

CREATE TABLE statistic_queries (
                                          type smallint,
                                          created_at timestamp(6) with time zone,
                                          id bigint NOT NULL,
                                          updated_at timestamp(6) with time zone,
                                          description text,
                                          name character varying(255),
                                          query text,
                                          CONSTRAINT statistic_queries_type_check CHECK (((type >= 0) AND (type <= 2)))
);

ALTER TABLE statistic_queries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME statistic_queries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE support_ticket_categories (
                                                  created_at timestamp(6) with time zone,
                                                  id bigint NOT NULL,
                                                  updated_at timestamp(6) with time zone,
                                                  name character varying(255)
);

ALTER TABLE support_ticket_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME support_ticket_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE support_ticket_urgencies (
                                                 created_at timestamp(6) with time zone,
                                                 id bigint NOT NULL,
                                                 updated_at timestamp(6) with time zone,
                                                 name character varying(255)
);

ALTER TABLE support_ticket_urgencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME support_ticket_urgencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE support_tickets (
                                        category_id bigint,
                                        created_at timestamp(6) with time zone,
                                        id bigint NOT NULL,
                                        updated_at timestamp(6) with time zone,
                                        urgency_id bigint,
                                        content text,
                                        email character varying(255),
                                        status character varying(255),
                                        subject character varying(255),
                                        CONSTRAINT support_tickets_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'ON_HOLD'::character varying, 'CLOSED'::character varying])::text[])))
);

ALTER TABLE support_tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME support_tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE user_roles (
                                   role_id bigint NOT NULL,
                                   user_id bigint NOT NULL
);

CREATE TABLE users (
                              created_at timestamp(6) with time zone,
                              id bigint NOT NULL,
                              updated_at timestamp(6) with time zone,
                              email character varying(255),
                              emojis character varying(255),
                              first_name character varying(255),
                              last_name character varying(255),
                              password_hash character varying(255),
                              status character varying(255),
                              username character varying(255),
                              CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_VERIFICATION'::character varying, 'PENDING_APPROVAL'::character varying, 'ACTIVE'::character varying, 'SUSPENDED'::character varying, 'ARCHIVED'::character varying, 'DELETED'::character varying, 'REJECTED'::character varying])::text[])))
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE verification_sessions (
                                              attempts integer NOT NULL,
                                              created_at timestamp(6) with time zone,
                                              expires_at timestamp(6) with time zone,
                                              id bigint NOT NULL,
                                              last_sent_at timestamp(6) with time zone,
                                              updated_at timestamp(6) with time zone,
                                              user_id bigint,
                                              uuid uuid,
                                              code_hash character varying(255),
                                              type character varying(255),
                                              CONSTRAINT verification_sessions_type_check CHECK (((type)::text = ANY ((ARRAY['VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying])::text[])))
);

ALTER TABLE verification_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME verification_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY configuration
    ADD CONSTRAINT configuration_key_key UNIQUE (key);

ALTER TABLE ONLY configuration
    ADD CONSTRAINT configuration_pkey PRIMARY KEY (id);

ALTER TABLE ONLY content_templates
    ADD CONSTRAINT content_templates_name_key UNIQUE (name);

ALTER TABLE ONLY content_templates
    ADD CONSTRAINT content_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY content_templates
    ADD CONSTRAINT content_templates_type_key UNIQUE (type);

ALTER TABLE ONLY email_templates
    ADD CONSTRAINT email_templates_name_key UNIQUE (name);

ALTER TABLE ONLY email_templates
    ADD CONSTRAINT email_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY email_templates
    ADD CONSTRAINT email_templates_type_key UNIQUE (type);

ALTER TABLE ONLY exceptions
    ADD CONSTRAINT exceptions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY faq
    ADD CONSTRAINT faq_name_key UNIQUE (name);

ALTER TABLE ONLY faq
    ADD CONSTRAINT faq_pkey PRIMARY KEY (id);

ALTER TABLE ONLY item_bookings
    ADD CONSTRAINT item_bookings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY item_categories
    ADD CONSTRAINT item_categories_name_key UNIQUE (name);

ALTER TABLE ONLY item_categories
    ADD CONSTRAINT item_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY items
    ADD CONSTRAINT items_name_key UNIQUE (name);

ALTER TABLE ONLY items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY lockers
    ADD CONSTRAINT lockers_index_key UNIQUE (index);

ALTER TABLE ONLY lockers
    ADD CONSTRAINT lockers_name_key UNIQUE (name);

ALTER TABLE ONLY lockers
    ADD CONSTRAINT lockers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);

ALTER TABLE ONLY roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY roles
    ADD CONSTRAINT roles_type_key UNIQUE (type);

ALTER TABLE ONLY room_bookings
    ADD CONSTRAINT room_bookings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY room_bookings_whitelisted_users
    ADD CONSTRAINT room_bookings_whitelisted_users_pkey PRIMARY KEY (room_booking_id, user_id);

ALTER TABLE ONLY statistic_queries
    ADD CONSTRAINT statistic_queries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY support_ticket_categories
    ADD CONSTRAINT support_ticket_categories_name_key UNIQUE (name);

ALTER TABLE ONLY support_ticket_categories
    ADD CONSTRAINT support_ticket_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY support_ticket_urgencies
    ADD CONSTRAINT support_ticket_urgencies_name_key UNIQUE (name);

ALTER TABLE ONLY support_ticket_urgencies
    ADD CONSTRAINT support_ticket_urgencies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY support_tickets
    ADD CONSTRAINT support_tickets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (role_id, user_id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_emojis_key UNIQUE (emojis);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_username_key UNIQUE (username);

ALTER TABLE ONLY verification_sessions
    ADD CONSTRAINT verification_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY verification_sessions
    ADD CONSTRAINT verification_sessions_uuid_key UNIQUE (uuid);

ALTER TABLE ONLY item_bookings
    ADD CONSTRAINT fk3x7rundw8hvnqhnu9ejs4jdo2 FOREIGN KEY (item_id) REFERENCES items(id);

ALTER TABLE ONLY room_bookings_whitelisted_users
    ADD CONSTRAINT fk68byt6yn2oldrac0iwlb0wejf FOREIGN KEY (room_booking_id) REFERENCES room_bookings(id);

ALTER TABLE ONLY room_bookings_whitelisted_users
    ADD CONSTRAINT fk7alk4c369mnui2kvopgutn07h FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY support_tickets
    ADD CONSTRAINT fkdlrj6yql4pk7m093ka2vo5pmm FOREIGN KEY (category_id) REFERENCES support_ticket_categories(id);

ALTER TABLE ONLY items
    ADD CONSTRAINT fkex02ttpcokc9eaarv8woas8ql FOREIGN KEY (category_id) REFERENCES item_categories(id);

ALTER TABLE ONLY user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES roles(id);

ALTER TABLE ONLY user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY room_bookings
    ADD CONSTRAINT fkij8h49orrcde2c3irhnp2ekcm FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY audit_logs
    ADD CONSTRAINT fkjs4iimve3y0xssbtve5ysyef0 FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY item_bookings
    ADD CONSTRAINT fkm6oa8vh6q29yco67ufwr1uqee FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY items
    ADD CONSTRAINT fkmsgrv02g72t6sfbie7c6p0coe FOREIGN KEY (locker_id) REFERENCES lockers(id);

ALTER TABLE ONLY role_permissions
    ADD CONSTRAINT fkn5fotdgk8d1xvo8nav9uv3muc FOREIGN KEY (role_id) REFERENCES roles(id);

ALTER TABLE ONLY support_tickets
    ADD CONSTRAINT fkpgl9wvsbl6otj3x5rqjxv4gmh FOREIGN KEY (urgency_id) REFERENCES support_ticket_urgencies(id);

ALTER TABLE ONLY verification_sessions
    ADD CONSTRAINT fkqbdyfq03emollf3uvpcr1eqv6 FOREIGN KEY (user_id) REFERENCES users(id);