spring:
  application.name: TUrtleAPI
  jpa.hibernate.ddl-auto: validate
  flyway.locations: classpath:flyway/migrations
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_SERVER}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties.mail.smtp:
      auth: ${SMTP_SECURE}
      ssl.enable: ${SMTP_SECURE}

server.forward-headers-strategy: none

springdoc:
  api-docs.path: /openapi/api-docs
  swagger-ui:
    url: /openapi/api-docs
    path: /docs
    operations-sorter: alpha
    tagsSorter: alpha