spring:
  application:
    name: TUrtleAPI

  security:
    oauth2:
      client:
        provider:
          tu-darmstadt:
            issuer-uri: https://login-test.hrz.tu-darmstadt.de
            authorization-uri: https://login-test.hrz.tu-darmstadt.de/idp/profile/oidc/authorize
            token-uri: https://login-test.hrz.tu-darmstadt.de/idp/profile/oidc/token
            user-info-uri: https://login-test.hrz.tu-darmstadt.de/idp/profile/oidc/userinfo
            jwk-set-uri: https://login-test.hrz.tu-darmstadt.de/idp/profile/oidc/keyset
            user-name-attribute: sub

        registration:
          tu-darmstadt:
            client-name: TU Darmstadt Login
            client-id: a
            client-secret: b
            redirect-uri: "{baseUrl}/auth/oauth2/code/{registrationId}" # http://localhost/api/auth/oauth2/code/tu-darmstadt
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_SERVER}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  mustache:
    check-template-location: false

springdoc:
  api-docs:
    path: /openapi/api-docs
  swagger-ui:
    url: /openapi/api-docs
    path: /docs

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        path: /api
        same-site: none
        secure: false # TODO change to true when in production
      timeout: 30m

turtle:
  security:
    max-sessions: 16
    session-secret: F~jU}3x]&Y@{LZgn:'!uWMmFhmZEySZZ{p9ve&Y]gDa,Pg[:^pv_T)s'=R+3{/d9
  debug: false #TODO remove in prod
  ssh:
    door:
      host: 192.168.0.107
      port: 22
      username: pi
      password: Start123
    locker:
      host: 192.168.0.107
      port: 22
      username: pi
      password: Start123
